# -*- coding: utf-8 -*-
# *** Spyder Python Console History Log ***

## ---(Fri Feb 16 23:31:39 2024)---
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/temp.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled0.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled2.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled3.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled4.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled5.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')

## ---(Sat Feb 17 02:35:05 2024)---
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone2.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')

## ---(Sat Feb 17 08:31:49 2024)---
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone2.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled0.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')

## ---(Tue Feb 20 10:29:15 2024)---
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled0.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone3.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone2new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone4.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled4.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled5.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4threeAcc.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled6.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4threeAcc.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled6.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4threeAcc.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled6.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled7.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled6.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled7.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled6.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')

## ---(Tue Mar  5 17:56:27 2024)---
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone3.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled0.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone3.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled0.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4threeAcc.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled3.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled4.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled4.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled4.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milstone4new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled4.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/ml4graph2.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone2new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled5.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone6.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone3new.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled8.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestonetry.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone6.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestonetry.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')

## ---(Tue Apr  9 11:22:36 2024)---
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone5.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled2.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled2.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled1.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled2.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone5.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/ms5try.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled3.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone5.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled3.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone5.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled3.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone5.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled3.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/untitled4.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone6.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestonetry.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')
runfile('/Users/pragnaboyallaramamurthy/.spyder-py3/milestone6.py', wdir='/Users/pragnaboyallaramamurthy/.spyder-py3')